
services:
  psqldb:                   
    image: 'postgres:latest'
    container_name: database
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      - psqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psqldb:5432/myuser
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
      - '5005:5005'
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4200:4200"
  bot-framework:
    build:
      context: ./bot-framework
    ports:
      - "3978:3978"