volumes:
  db_data:
services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
    - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4200:4200"
  bot-framework:
    build:
      context: ./bot-framework
    ports:
      - "3978:3978"